title: University of Toronto</br> Applied Deep Learning
description: Applied Deep Learning

url: //chl7001-adl.github.io
baseurl:
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Grading
   url: /grading
 - title: Schedule
   url: /schedule