title: space2vec
description: Clustering the goddamn universe

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: space2vec
   twitter: space2vec
   facebook: space2vec
   email: pl@deeplearni.ng

google_analytics: ""
